"""add_zona_evento_to_event_model

Revision ID: 644827b2c66a
Revises: e628e91b9577
Create Date: 2025-05-27 00:01:33.949782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644827b2c66a'
down_revision = 'e628e91b9577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona_evento', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('zona_evento')

    # ### end Alembic commands ###
