"""add_incident_fields_and_assignment_model

Revision ID: de8146e6890c
Revises: 20d9a029502d
Create Date: 2024-05-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8146e6890c'
down_revision = '20d9a029502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # La base de datos del servidor ya parece tener estos cambios,
    # así que esta función de upgrade se deja vacía para evitar errores.
    # Simplemente se marcará esta revisión como aplicada.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Si se hiciera downgrade, se asumiría que los cambios existían.
    # Comentado para seguridad, ya que el estado exacto de la BD es incierto.
    # with op.batch_alter_table('incidents', schema=None) as batch_op:
    #     batch_op.drop_column('fecha_finalizado')
    #     batch_op.drop_column('fecha_stand_by')
    #     batch_op.drop_column('fecha_activado')
    #     batch_op.drop_column('fecha_pre_activado')
    # op.drop_table('incident_assignments')
    pass
    # ### end Alembic commands ### 