"""add_incident_fields_and_assignment_model

Revision ID: de8146e6890c
Revises: 20d9a029502d
Create Date: 2024-05-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8146e6890c'
down_revision = '20d9a029502d' # Esto debe apuntar al ID de tu última migración real
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pre_activado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_activado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_stand_by', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_finalizado', sa.DateTime(), nullable=True))

    op.create_table('incident_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('indicativo_id', sa.Integer(), nullable=False),
    sa.Column('estado_asignacion', sa.String(length=32), nullable=True),
    sa.Column('fecha_creacion_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_pre_avisado_asig', sa.DateTime(), nullable=True),
    sa.Column('fecha_avisado_asig', sa.DateTime(), nullable=True),
    sa.Column('fecha_en_camino_asig', sa.DateTime(), nullable=True),
    sa.Column('fecha_en_lugar_asig', sa.DateTime(), nullable=True),
    sa.Column('fecha_finalizado_asig', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['indicativo_id'], ['indicativos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('fecha_finalizado')
        batch_op.drop_column('fecha_stand_by')
        batch_op.drop_column('fecha_activado')
        batch_op.drop_column('fecha_pre_activado')

    op.drop_table('incident_assignments')
    # ### end Alembic commands ### 