"""add info_ubicacion and servicio_nombre

Revision ID: f84c9e8
Revises: 644827b2c66a
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84c9e8'
down_revision = '644827b2c66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info_ubicacion', sa.Text(), nullable=True))

    with op.batch_alter_table('incident_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio_nombre', sa.String(length=100), nullable=True))
        batch_op.alter_column('indicativo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_assignments', schema=None) as batch_op:
        batch_op.alter_column('indicativo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('servicio_nombre')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('info_ubicacion')
    # ### end Alembic commands ### 